import type { Metadata } from 'next'
import { Metrophobic } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Provider'
import NavBar from '@/components/NavBar'

const metrophobic = Metrophobic({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{
  return (
    <html lang="en">
      <body className={`${metrophobic.className} text-4xl text-zinc-800`}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
